### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by fhibler** [tdorssers/TeslaPy#4]
Hi,
I'll get a traceback, as the GPS information of my car seems to resolve to a location which contains an Umlaut (in this case 'ü').

Happy to provide further details and thanks for this fairly cool tool!

```
Traceback (most recent call last):
  File "menu.py", line 259, in <module>
    main()
  File "menu.py", line 256, in main
    menu(vehicles[idx])
  File "menu.py", line 151, in menu
    show_vehicle_data(vehicle.get_vehicle_data())
  File "menu.py", line 87, in show_vehicle_data
    print('GPS: {:.75}'.format(str(location)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 10: ordinal not in range(128)

```

**Comment by tdorssers** [comment]
Thanks for opening this issue. The error should be resolved in the last commit.
