### ISSUE TITLE
Unable to login using CLI on macOS 12.5 (Monterey)

### ISSUE THREAD

**Issue by shred86** [tdorssers/TeslaPy#94]
Using cli.py, after `python3 cli.py -e my@email.com -s`, a new window opens with a Tesla Sign In screen with my email address populated. However, I'm unable to type anything in the password field. It's almost like the screen is completely non-responsive but sometimes I notice if I click around enough, I'll get some interaction for a second then it freezes again making it impossible to type or paste in a password.

Update:

So this appears to be an [issue](https://github.com/r0x0r/pywebview/issues/66) with pywebview when using virtual environments. However, even outside of a virtual environment I was having the same issue.

I tried adding `--chrome` to see if I could use Chrome via Selenium but that results in:

````
Traceback (most recent call last):
  File "cli.py", line 189, in <module>
    main()
  File "cli.py", line 61, in main
    selected = prod = tesla.vehicle_list() + tesla.battery_list()
  File "/Users/myuser/Projects/TeslaPy/teslapy/__init__.py", line 371, in vehicle_list
    return [Vehicle(v, self) for v in self.api('VEHICLE_LIST')['response']]
  File "/Users/myuser/Projects/TeslaPy/teslapy/__init__.py", line 356, in api
    self.fetch_token()
  File "/Users/myuser/Projects/TeslaPy/teslapy/__init__.py", line 223, in fetch_token
    kwargs['authorization_response'] = self.authenticator(url)
  File "cli.py", line 39, in custom_auth
    options = [webdriver.chrome, webdriver.opera,
AttributeError: module 'selenium.webdriver' has no attribute 'opera'
````

So I removed references to `opera` as the selenium 4.0+ documentation mentions to just use the ChromeDriver for Opera (and I'm not using Opera). That led to the following error:

````
  File "cli.py", line 41, in custom_auth
    with [webdriver.Chrome, webdriver.Edge][args.web](options=options) as browser:
  File "/Users/myuser/Projects/venv/tesla/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "/Users/myuser/Projects/venv/tesla/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/Users/myuser/Projects/venv/tesla/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
````

I then realized I had to install ChromeDriver, which for Mac OS I used `brew install chromedriver`. Now it was being blocked by Mac OS security so I had to go to the OS security settings and set "Allow apps downloaded from:" to "App Store". After a few more warnings and errors when ChromeDriver was attempting to run, it's finally working.

**Comment by shred86** [comment]
So it turns out using Python installed via Anaconda was also causing the issues with pywebview. I uninstalled Anaconda and made sure I was using Python installed via homebrew and it seems to work now. So the fix to the original issue is, don't try to run pywebview inside a virtual env or using Python via Anaconda.
